import 'package:bourgo_arena_mobile/core/di/locator.dart';
import 'package:bourgo_arena_mobile/core/theme/bourgo_theme.dart';
import 'package:bourgo_arena_mobile/data/services/auth_service.dart';
import 'package:bourgo_arena_mobile/domain/entities/user.dart';
import 'package:bourgo_arena_mobile/l10n/app_localizations.dart';
import 'package:bourgo_arena_mobile/presentation/auth/widgets/auth_header.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';

/// Screen for setting up a gym entry PIN.
class PinSetupScreen extends StatefulWidget {
  /// Registration data passed from previous steps.
  final Map<String, dynamic> registrationData;

  /// Creates a [PinSetupScreen].
  const PinSetupScreen({super.key, required this.registrationData});

  @override
  State<PinSetupScreen> createState() => _PinSetupScreenState();
}

class _PinSetupScreenState extends State<PinSetupScreen> {
  final List<TextEditingController> _controllers = List.generate(
    4,
    (_) => TextEditingController(),
  );
  final List<FocusNode> _focusNodes = List.generate(4, (_) => FocusNode());

  @override
  void dispose() {
    for (var controller in _controllers) {
      controller.dispose();
    }
    for (var node in _focusNodes) {
      node.dispose();
    }
    super.dispose();
  }

  Future<void> _onFinish() async {
    final pin = _controllers.map((e) => e.text).join();
    if (pin.length == 4) {
      final authService = locator<AuthService>();

      try {
        // Construct a User object from registration data
        // For now, we fill in some mock data for fields that would be
        // generated by the backend or aren't collected in the flow yet.
        final user = User(
          id: 'temp-id-${DateTime.now().millisecondsSinceEpoch}',
          firstName: widget.registrationData['firstName'] ?? '',
          lastName: widget.registrationData['lastName'] ?? '',
          email: widget.registrationData['email'] ?? '',
          phone: widget.registrationData['phone'] ?? '',
          avatarUrl:
              'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=2574&auto=format&fit=crop',
          loyaltyPoints: 0,
          subscriptionLevel: 'FREE',
          subscriptionExpiry: 'N/A',
          totalCheckIns: 0,
          isParentAccount: widget.registrationData['isParentAccount'] ?? false,
          children: const [],
        );

        await authService.completeRegistration(user);

        if (mounted) {
          context.go('/home');
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(AppLocalizations.of(context)!.commonErrorOccurred),
              backgroundColor: Theme.of(context).colorScheme.error,
            ),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final l10n = AppLocalizations.of(context)!;

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        automaticallyImplyLeading: false,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              AuthHeader(
                title: l10n.authPinSetupTitle,
                subtitle: l10n.authPinSetupSubtitle,
              ),
              const SizedBox(height: 64),

              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: List.generate(4, (index) => _buildPinField(index)),
              ),

              const Spacer(),

              Text(
                l10n.authPinSetupInstruction,
                textAlign: TextAlign.center,
                style: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
              const SizedBox(height: 32),

              ListenableBuilder(
                listenable: locator<AuthService>(),
                builder: (context, _) {
                  final isLoading = locator<AuthService>().isLoading;
                  return ElevatedButton(
                    onPressed: isLoading ? null : _onFinish,
                    child: isLoading
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : Text(l10n.authCompleteRegistration),
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildPinField(int index) {
    final theme = Theme.of(context);
    final appColors = theme.extension<AppColors>()!;

    return SizedBox(
      width: 72,
      height: 80,
      child: TextField(
        controller: _controllers[index],
        focusNode: _focusNodes[index],
        keyboardType: TextInputType.number,
        textAlign: TextAlign.center,
        maxLength: 1,
        obscureText: true,
        style: theme.textTheme.headlineMedium?.copyWith(
          fontWeight: FontWeight.bold,
          color: theme.colorScheme.onSurface,
        ),
        inputFormatters: [FilteringTextInputFormatter.digitsOnly],
        decoration: InputDecoration(
          counterText: '',
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: appColors.bgBorder, width: 2),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: theme.colorScheme.primary, width: 2),
          ),
          filled: true,
          fillColor: appColors.bgElevated,
        ),
        onChanged: (value) {
          if (value.isNotEmpty && index < 3) {
            _focusNodes[index + 1].requestFocus();
          } else if (value.isEmpty && index > 0) {
            _focusNodes[index - 1].requestFocus();
          }

          if (index == 3 && value.isNotEmpty) {
            _focusNodes[index].unfocus();
          }
        },
      ),
    );
  }
}
