// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-59flQQj9gpZ2WQ90cg1t40bh2SOxKY',
    appId: '1:892901134215:web:909a99874f1b939ec40d22',
    messagingSenderId: '892901134215',
    projectId: 'bourgo-arena',
    authDomain: 'bourgo-arena.firebaseapp.com',
    storageBucket: 'bourgo-arena.firebasestorage.app',
    measurementId: 'G-L9B1PMFNDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCH_FZ8BBjZVm__mGwWXjbG-QuQav6YE',
    appId: '1:892901134215:android:25b40bf4da062256c40d22',
    messagingSenderId: '892901134215',
    projectId: 'bourgo-arena',
    storageBucket: 'bourgo-arena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SMDicGNKQlbfXMWH0qNEThoQHmWBilY',
    appId: '1:892901134215:ios:d1d241c4ebd5c72bc40d22',
    messagingSenderId: '892901134215',
    projectId: 'bourgo-arena',
    storageBucket: 'bourgo-arena.firebasestorage.app',
    iosBundleId: 'com.example.bourgoArenaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6SMDicGNKQlbfXMWH0qNEThoQHmWBilY',
    appId: '1:892901134215:ios:d1d241c4ebd5c72bc40d22',
    messagingSenderId: '892901134215',
    projectId: 'bourgo-arena',
    storageBucket: 'bourgo-arena.firebasestorage.app',
    iosBundleId: 'com.example.bourgoArenaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw-59flQQj9gpZ2WQ90cg1t40bh2SOxKY',
    appId: '1:892901134215:web:cf060943955375fbc40d22',
    messagingSenderId: '892901134215',
    projectId: 'bourgo-arena',
    authDomain: 'bourgo-arena.firebaseapp.com',
    storageBucket: 'bourgo-arena.firebasestorage.app',
    measurementId: 'G-74S19CYDL4',
  );
}
